spring.application.name=ms-membresias
server.port=8081

spring.datasource.url=jdbc:h2:mem:membresiasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/gimnasio
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/gimnasio/protocol/openid-connect/certs

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.enable-auto-commit=false
